
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloIndigoService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost/wsdl/HelloIndigo.wsdl")
public class HelloIndigoService
    extends Service
{

    private final static URL HELLOINDIGOSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOINDIGOSERVICE_EXCEPTION;
    private final static QName HELLOINDIGOSERVICE_QNAME = new QName("http://tempuri.org/", "HelloIndigoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	//real HTTP service
            //url = new URL("http://localhost:8000/HelloIndigoService?wsdl");
            
            //routing HTTP service. Not working.
            //url = new URL("http://WIN-C088QGABQ4R:2345/RoutingService/HelloIndigoRouter");
            
        	//use local wsdl file
            url = new URL("http://localhost/wsdl/HelloIndigo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOINDIGOSERVICE_WSDL_LOCATION = url;
        HELLOINDIGOSERVICE_EXCEPTION = e;
    }

    public HelloIndigoService() {
        super(__getWsdlLocation(), HELLOINDIGOSERVICE_QNAME);
    }

    public HelloIndigoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOINDIGOSERVICE_QNAME, features);
    }

    public HelloIndigoService(URL wsdlLocation) {
        super(wsdlLocation, HELLOINDIGOSERVICE_QNAME);
    }

    public HelloIndigoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOINDIGOSERVICE_QNAME, features);
    }

    public HelloIndigoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloIndigoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHelloIndigoService
     */
    @WebEndpoint(name = "BasicHttpBinding_IHelloIndigoService")
    public IHelloIndigoService getBasicHttpBindingIHelloIndigoService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IHelloIndigoService"), IHelloIndigoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloIndigoService
     */
    @WebEndpoint(name = "BasicHttpBinding_IHelloIndigoService")
    public IHelloIndigoService getBasicHttpBindingIHelloIndigoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IHelloIndigoService"), IHelloIndigoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOINDIGOSERVICE_EXCEPTION!= null) {
            throw HELLOINDIGOSERVICE_EXCEPTION;
        }
        return HELLOINDIGOSERVICE_WSDL_LOCATION;
    }

}
