
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISecureServiceBasicHttp", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ISecureServiceBasicHttp {


    /**
     * 
     * @param stringSecure
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloSecure", action = "http://tempuri.org/ISecureServiceBasicHttp/HelloSecure")
    @WebResult(name = "HelloSecureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloSecure", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloSecure")
    @ResponseWrapper(localName = "HelloSecureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloSecureResponse")
    public String helloSecure(
        @WebParam(name = "stringSecure", targetNamespace = "http://tempuri.org/")
        String stringSecure);

}
