
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.BindingType;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService2", targetNamespace = "http://tempuri.org/")
@BindingType(value="http://java.sun.com/xml/ns/jaxws/2003/05/soap/bindings/HTTP/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IService2 {


    /**
     * 
     * @param s
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello", action = "http://tempuri.org/IService2/Hello")
    @WebResult(name = "HelloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloResponse")
    @Action(input = "http://tempuri.org/IService2/Hello", output = "http://tempuri.org/IService2/HelloResponse")
    public String hello(
        @WebParam(name = "s", targetNamespace = "http://tempuri.org/")
        String s);

    /**
     * 
     * @param string
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello2", action = "http://tempuri.org/IService2/Hello2")
    @WebResult(name = "Hello2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Hello2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Hello2")
    @ResponseWrapper(localName = "Hello2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Hello2Response")
    @Action(input = "http://tempuri.org/IService2/Hello2", output = "http://tempuri.org/IService2/Hello2Response")
    public String hello2(
        @WebParam(name = "string", targetNamespace = "http://tempuri.org/")
        String string);

}
