
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecureServiceBasicHttp", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://win-c088qgabq4r:8123/SSLServiceBasicHttp?wsdl")
public class SecureServiceBasicHttp
    extends Service
{

    private final static URL SECURESERVICEBASICHTTP_WSDL_LOCATION;
    private final static WebServiceException SECURESERVICEBASICHTTP_EXCEPTION;
    private final static QName SECURESERVICEBASICHTTP_QNAME = new QName("http://tempuri.org/", "SecureServiceBasicHttp");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://win-c088qgabq4r:8123/SSLServiceBasicHttp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURESERVICEBASICHTTP_WSDL_LOCATION = url;
        SECURESERVICEBASICHTTP_EXCEPTION = e;
    }

    public SecureServiceBasicHttp() {
        super(__getWsdlLocation(), SECURESERVICEBASICHTTP_QNAME);
    }

    public SecureServiceBasicHttp(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURESERVICEBASICHTTP_QNAME, features);
    }

    public SecureServiceBasicHttp(URL wsdlLocation) {
        super(wsdlLocation, SECURESERVICEBASICHTTP_QNAME);
    }

    public SecureServiceBasicHttp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURESERVICEBASICHTTP_QNAME, features);
    }

    public SecureServiceBasicHttp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecureServiceBasicHttp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISecureServiceBasicHttp
     */
    @WebEndpoint(name = "BasicHttpBinding_ISecureServiceBasicHttp")
    public ISecureServiceBasicHttp getBasicHttpBindingISecureServiceBasicHttp() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISecureServiceBasicHttp"), ISecureServiceBasicHttp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISecureServiceBasicHttp
     */
    @WebEndpoint(name = "BasicHttpBinding_ISecureServiceBasicHttp")
    public ISecureServiceBasicHttp getBasicHttpBindingISecureServiceBasicHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISecureServiceBasicHttp"), ISecureServiceBasicHttp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURESERVICEBASICHTTP_EXCEPTION!= null) {
            throw SECURESERVICEBASICHTTP_EXCEPTION;
        }
        return SECURESERVICEBASICHTTP_WSDL_LOCATION;
    }

}
